name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Super das du mir ein Issue schreibts"
        pr-message: " ... irgendwas"

        uses: cinotify/github-action@main
        with:
          to: 'tooktook2014@gmail.com'
          subject: 'building main'
          body: 'This is a notification from GitHub actions.'
          attachment: 'artifacts.zip'
